---
title: "animated cartogram"
output: html_notebook
---

```{r}
# Load libraries
library(tmap)
library(sf)
library(geojsonio)
library(dplyr)        # data wrangling
library(cartogram)    # for the cartogram
library(ggplot2)      # to realize the plots
library(broom)        # from geospatial format to data frame
library(tweenr)       # to create transition dataframe between 2 states
library(gganimate)    # To realize the animation
library(gifski)       # render gganimate as gif
library(maptools)     # world boundaries coordinates
library(viridis)      # for a nice color palette

```

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

spatial data
```{r}
spdf <- geojson_read("../data/external/lbth_oa21.geojson",  what = "sp")

```

census data
```{r}
lbth_popden_oa21 = read.csv('../data/external/lbth_census_2021_pop_density_oa.csv', header=TRUE)
```

merge
```{r}
lbth_popden_oa21['OA21CD'] = lbth_popden_oa21['GEOGRAPHY_CODE']
df = merge(spdf, lbth_popden_oa21, on='OA21CD')
```

create choropleth spatial data frame
```{r}
sfno <- st_as_sf(df)
choropleth <- st_transform(sfno, crs = 3857)
# st_crs(sfproj)
```

create cartogram spatial data frame
```{r}
cartogram <- cartogram_cont(choropleth, "OBS_VALUE", itermax = 5)

```

plot choropleth
```{r}
# choropleth
ggplot() +
  geom_sf(data = choropleth, aes(fill = OBS_VALUE, color=OBS_VALUE)) +
   scale_fill_viridis(direction = -1, label = scales::comma, option = "A") +
    scale_color_viridis(direction = -1, label = scales::comma, option = "A")

```

plot cartogram
```{r}
# cartogram
ggplot() +
  geom_sf(data = cartogram, aes(fill = OBS_VALUE, color=OBS_VALUE)) +
   scale_fill_viridis(direction = -1, label = scales::comma, option = "A") +
    scale_color_viridis(direction = -1, label = scales::comma, option = "A")

```


prepare animation

```{r}

# give each dataframe an id column
# id is used for animation tweening
cartogram$id <- 1 #seq(1,nrow(cartogram))
choropleth$id <- 2 #seq(1,nrow(choropleth))
 
# stack dataframes ready to tween
data <- rbind(choropleth, cartogram)

```

```{r}
# Plot
data$Population_density <- data$OBS_VALUE
pop_label <- expression(People ~ per ~ km^2)
```

```{r}
anim <- data %>% ggplot() + 
    geom_sf() + aes(fill = Population_density, color = Population_density) +
    scale_fill_viridis(name=pop_label, direction = -1, label = scales::comma, option = "A") +
    scale_color_viridis(name=pop_label, direction = -1, label = scales::comma, option = "A") +
    labs( title = "Tower Hamlets", subtitle="Cartogram of population density" ) +
    transition_states(id, transition_length = 2, state_length = 1) +
    theme(
      text = element_text(color = "#22211d"), 
      plot.background = element_rect(fill = "#f5f5f4", color = NA), 
      panel.background = element_rect(fill = "#f5f5f4", color = NA), 
      legend.background = element_rect(fill = "#f5f5f4", color = NA),
      plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
      plot.subtitle = element_text(size= 13, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
      axis.text.x=element_blank(), #remove x axis labels
      axis.ticks.x=element_blank(), #remove x axis ticks
      axis.text.y=element_blank(),  #remove y axis labels
      axis.ticks.y=element_blank()  #remove y axis ticks
    ) 
```

```{r}
anim
```


```{r}
# Video output
animate(
  anim + ease_aes('cubic-in-out'),
  # renders as a sequence of images
  # renderer = file_renderer(dir = "../data/interim/", prefix = "gganim_plot", overwrite = FALSE)
  # makes an animated gif
  renderer = gifski_renderer()
)
```

```{r}
anim_save("../data/processed/lbth_census21_pop_density.gif", anim)

```


